### ISSUE TITLE
Changes are needed to be compatible with up-to-date version of SLY dependency

### ISSUE THREAD

**Issue by frou** [spyoungtech/json-five#40]
Hi there - it seems the recent 0.5 release of the SLY dependency has broken json-five:

```txt
>>> json5.loads('{"foo": 123}')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/json5/loader.py", line 49, in loads
    model = parse_source(s)
  File "/usr/local/lib/python3.10/site-packages/json5/parser.py", line 479, in parse_source
    model = parse_tokens(tokens)
  File "/usr/local/lib/python3.10/site-packages/json5/parser.py", line 474, in parse_tokens
    return parser.parse(raw_tokens)
  File "/usr/local/lib/python3.10/site-packages/json5/parser.py", line 449, in parse
    model = super().parse(tokens)
  File "/usr/local/lib/python3.10/site-packages/sly/yacc.py", line 2148, in parse
    sym.end = symstack[-1].end
AttributeError: 'JSON5Token' object has no attribute 'end'
```

Perhaps the bug could be in SLY itself? But the situation for dependants is complicated by [this announcement](https://github.com/dabeaz/sly#important-notice--october-11-2022).

**Comment by spyoungtech** [comment]
Thanks for reporting this.

Yes, it definitely appears that changes in sly 0.5 has broken this package. I don't think it's a bug in sly, and I'm pretty sure I know how to fix the issue for us to be compatible with v0.5 of sly, but for the time being, I've released a small patch in version `0.7.6` of this package that pins the older version of sly.

**Comment by frou** [comment]
Thank you. The 0.7.6 release of `json-five` is working again.

**Comment by spyoungtech** [comment]
Should now be compatible with either version of `sly` in v0.8.0

Thanks!
